### ISSUE TITLE
--bro-no-notice flag or bro-no-notice config issue for bro

### ISSUE THREAD

**Issue by brianhaugli** [certau/cti-toolkit#12]
--bro-no-notice flag and setting "bro-no-notice: true" does not set "F" in formatted bro file.  Keeps as a "T" to still show in Notice framework.

**Comment by kralca** [comment]
Many thanks to @thisismyrobot - this issue is now fixed.

**Comment by kralca** [comment]
And thanks to @brianhaugli for reporting the issue.
